### ISSUE TITLE
PRACTICA 2_INTERFAZ GRÁFICA

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/practica-de-visual-studio-Eva155#2]
[Práctica 2_Interfaz Gráfica.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Eva155/files/6145069/Practica.2_Interfaz.Grafica.pdf)

**Comment by Abraham890** [comment]
Excelente trabajo el cual cumple con todos los puntos que marca la rúbrica es por ello que le asignó la siguiente:
Calificación: 100/100
Calificó: Abraham Reyes Ortiz

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
